### ISSUE TITLE
css variables for width and height do not work

### ISSUE THREAD

**Issue by FluffyDiscord** [Ennoriel/svelte-awesome-color-picker#31]
I have component like this

```svelte
<ColorPicker
        bind:hex={highlightColor}
        isAlpha={false}
        isInput={false}
        canChangeMode={false}
        isOpen
        isPopup={false}
        toRight
        components={ChromeVariant}
        style="--picker-height: 110px; --picker-width: 110px;"
/>
```

but the color picker is still 200px wide and tall, basically the css variables do nothing and I have to force overwrite it using
```css
    :global(div .color-picker .picker-wrapper) {
        height: 110px !important;
        width: 110px !important;
    }
 ```
 
 but then the select dot is overflowing the container
 
 
![image](https://github.com/Ennoriel/svelte-awesome-color-picker/assets/10332247/068636e0-c712-4fd8-be0d-0b945b620b65)
